<?php
namespace controllers;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\attributes\items\router\Post;

 /**
 * Controller TodosController
 **/
class TodosController extends ControllerBase{
	public function index(){}
	public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->menu();
    }

    
	#[Post(path: "TodosController/add")]
	public function addElement(){
		
	}


	#[Route(path: "todos/edit/{index}")]
	public function editElement($index){
		
	}


	#[Route(path: "todos/loadList/{uniqid}")]
	public function loadList($uniqid){
		
	}


	#[Route(path: "todos/delete/{index}")]
	public function deleteElement($index){
		
	}
	
	public function menu(){
		
		$this->loadView('TodosController/menu.html');

	}

	#[Get(path:"todos.new/{force}",name:"todos
	.new")]
    public function newList($force){
    }



	public function displayList(){
		
		$this->loadView('TodosController/displayList.html');

	}

}
