<?php
namespace controllers;
use Ubiquity\attributes\items\router\Get;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\attributes\items\router\Post;
use Ubiquity\controllers\Router;
use Ubiquity\utils\http\USession;

/**
 * Controller TodosController
 */
class TodosController extends ControllerBase{

    const CACHE_KEY = 'datas/lists/';
    const EMPTY_LIST_ID='not saved';
    const LIST_SESSION_KEY='list';
    const ACTIVE_LIST_SESSION_KEY='active-list';


    #[Route('_default',name: 'home')]
    public function index(){
        if(USession::exists(self::LIST_SESSION_KEY)) {
            $list=USession::get(self::LIST_SESSION_KEY,[]);
            return $this->displayList($list);
        }
        $this->showMessage('Bienvenue !','TodoList','info','info circle', [['url' =>Router::path('todos.new'),'caption'=>'Créer une nouv liste','style'=>'basic inverted']]);
    }

    #[Post(path: "todos/add",name: 'todos.add')]
    public function addElement(){

    }


    #[Get(path: "todos/delete/{index}", name: 'todos.delete')]
    public function deleteElement($index){

    }


    #[Post(path: "todos/edit/{index}",name: 'todos.edit')]
    public function editElement($index){

    }


    #[Get(path: "todos/loadList/{uniqid}",name: 'todos.loadList')]
    public function loadList($uniqid){

    }



    private function menu(){

        $this->loadView('TodosController/menu.html');

    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->menu();
    }


    #[Get(path: "todos/new/{force}",name: 'dodos.new')]
    public function newList($force = false){

    }


    #[Get(path: "todos/saveList")]
    public function saveList(){

    }


    #[Post(path: "todos/loadList/")]
    public function loadListFromForm(){

    }



    private function displayList($list){

        $this->loadView('TodosController/displayList.html', ['list'=>$list]);

    }

    public function showMessage(string $header,string $message,string $type='info',string $icon='info circle',array $buttons=[]){

        $this->loadView('TodosController/showMessage.html',compact('header','type','icon','message','buttons'));

    }

}
